version: '3.5'

services:
    db:
        image: postgres
        volumes:
            - postgrevolume:/var/lib/postgresql/data
        expose:
            - "5432"
        env_file: .env
    web:
        restart: always
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        env_file: .env
        volumes:
            - .:/pollapp
        ports:
            - "3000:3000"
        depends_on: 
            - db
volumes: 
    postgrevolume: