default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['SQL_LOCAL_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['SQL_TEST_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['SQL_PROD_DATABASE'] %>
